#!/usr/bin/env bash

currentStep=node
unameOut=$(uname -s)

startStep
linkStepFiles

pkgs=(terminal-image-cli ncu)
case "${unameOut}" in
    CYGWIN*)    pkgs+=(npm-completion@windows) ;;
    MINGW*)     pkgs+=(npm-completion@windows) ;;
    *)          pkgs+=(npm-completion)         ;;
esac
log "installing \e[35m${pkgs[*]}\e[39m globally"
if [ "$dryRun" = false ] ; then
  npm i -g ${pkgs[*]}
fi
endStep
