# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

with lib;

{
  imports = [ <nixpkgs/nixos/modules/installer/cd-dvd/sd-image-raspberrypi4.nix> ];

  # Undo some unwanted options from the preset
  services.openssh = {
    permitRootLogin = mkOverride 10 "no";
  };
  systemd.services.sshd.wantedBy = mkOverride 10 (if config.services.openssh.startWhenNeeded then ["multi-user.target"] else ["sockets.target"]);
  security.sudo.wheelNeedsPassword = mkOverride 10 true;

  boot.initrd.availableKernelModules = [ "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
