# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  networking.useDHCP = false;
  networking.interfaces.enp2s0.useDHCP = true;

  # networking.wireless.enable = true; # Enables wireless support via wpa_supplicant.
  # networking.wireless.userControlled.enable = true;

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/73a797da-cc05-4a0b-83d6-78015b437e64";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D4AC-A2CE";
      fsType = "vfat";
    };

  fileSystems."/home/Myhlamaeus/media/games" =
    { device = "/dev/disk/by-partlabel/games";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/66a12fd4-a77a-4b64-8b07-484999ee0e50"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
